Major_Project/Controllers/AnalysisController.cs
using Major_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Major_Project.Controllers
{
    public class JsonClass
    {
        public List<string> label { get; set; }
        public int x2 { get; set; }
        public int y2 { get; set; }
        public JsonClass()
        {
            this.label = new List<string>();
        }
    }
    
    public class AnalysisController : Controller
    {
        //
        // POST: /Analysis/
        public ActionResult Index(int? id)
        {
            int tempId;// used to store the generated random numbers Through Random objt
            Random random = new Random();
            Major_ProjectEntities db = new Major_ProjectEntities();      
            //db.sp_emptyall();
            //db.sp_stepfirst();
            //db.sp_stepsecond("item_id1","item_id2");
            //db.sp_movetofinalAmerge(2);

            db.sp_emptyall();
            db.sp_stepfirst();
            db.sp_stepsecond("item_id1", "item_id2");
            db.sp_movetofinalAmerge(2);

            //db.sp_refresh();
            ////db.sp_stepfirst();
            //db.sp_stepsecond("item_id2", "item_id3");
            //db.sp_movetofinalAmerge(3);


            List<string> result = db.prune().ToList();
            List<string> str = new List<string>();
            List<string> final = new List<string>();
            int state = 0;
            int counter = 0;
            foreach (string rslt in result)
            {
                str.AddRange(rslt.Split(',').ToList());
                foreach(string s in str)
                {
                    counter++;
                    if (id ==int.Parse(s))
                    {
                        state = 1;
                        break;
                    }
                }  
                if(state==1)
                {
                    str.RemoveAt(counter - 1);
                    final.AddRange(str);
                }
                state = 0;
                counter = 0;
                str.Clear();
            }
            List<item> itm = new List<item>();  //items to be returned
            if (final.Count() < 1)
            {
                for (int i = 0; i < 12; i++)
                {


                    tempId = random.Next(db.tbl_const.Select(x => x.item_id).Min(), db.tbl_const.Select(x => x.item_id).Max());
                    var othersObject = (from m in db.items where m.item_id == tempId select m).Single();
                    itm.Add(new item()
                    {
                        item_id = tempId,
                        item_name = othersObject.item_name,
                        item_price = othersObject.item_id
                    }
                     );

                }
            }
            else
            {
                var distinct = final.Select(x => x).Distinct();
                foreach (string strr in distinct.ToList())
                {
                    foreach (var item in db.items.ToList())
                    {
                        if (item.item_id == int.Parse(strr))
                        {
                            itm.Add(item);
                        }
                    }
                }
            }
            

            //details data
           var data = (from m in db.items where m.item_id==id select m).Single();
           ViewBag.ID = data.item_id;
           ViewBag.Name = data.item_name;
           ViewBag.Category = data.category;
           ViewBag.Price = data.item_price;

            //for others 
           var itmlist = new List<item>();
           
           
           
           for (int i = 0; i < 12;i++)
           {


               tempId  = random.Next(db.tbl_const.Select(x => x.item_id).Min(), db.tbl_const.Select(x => x.item_id).Max());
               var othersObject = (from m in db.items where m.item_id == tempId select m).Single();
               itmlist.Add(new item()
               {
                   item_id = tempId,
                   item_name = othersObject.item_name,
                   item_price = othersObject.item_id
               }
                );
              
           }
               
           
           
          
           ViewBag.items = itmlist;

           return View(itm);
        }
        
        public ActionResult ShowChart(int id)
        {
            
            //int id=167;

            List<JsonClass> returnObject = new List<JsonClass>();
            Major_ProjectEntities db = new Major_ProjectEntities();
          // List<int> count= db.count_itemcount().ToList();
            List<int> count= new List<int>();
            var counter = db.count_itemcount().ToList();
            foreach(int t in counter)
            {
                count.Add(t);
            }
                    
            List<string> merged_result= db.count_itemname().ToList();
            List<string> tempStr= new List<string>();
            List<int> existentindex=new List<int>(); //index later used during count access to skip non existent data
            int mergedindex = 0;//tracks the location of current mergeditem
            int state = 0;//boolean to indicate existence and inexistence
            int innercounter = 0;//used to store the index location of the searched item for removal
            int nooItems = 0; // counter for 5 items of concern
            foreach (string str in merged_result)//for  1
            {       
                tempStr.AddRange(str.Split(','));
                foreach(string s in tempStr)
                {
                    if(id == int.Parse(s))
                    {
                        existentindex.Add(mergedindex);
                        state = 1;
                        break;
                    }
                    ++innercounter;
                }
                
                if(state==1)
                {
                    tempStr.RemoveAt(innercounter);

                    JsonClass tempObj = new JsonClass();
                    foreach (string s in tempStr)
                    {
                        foreach (var item in db.items.ToList())
                        {
                            if (item.item_id == int.Parse(s))
                            {
                                tempObj.label.Add(item.item_name);
                            }
                        }
                    }
                   
                    ///tempObj.label.AddRange(tempStr);

                    returnObject.Add(tempObj);
                    ++nooItems;
                    state = 0;
                }
                if (nooItems >4)
                {
                    break;
                }
                innercounter = 0;
                tempStr.Clear();
                ++mergedindex;
            }//end of for 1
            int x2 = 100;
           for(int i=0;i<returnObject.Count();i++) //for 2
           {
               returnObject[i].x2 = x2;
               returnObject[i].y2 = count[existentindex[i]];
               x2 += 100;

           }//end of for 2
           //List<JsonClass> fiveresults = new List<JsonClass>();

           
           return Json(returnObject, JsonRequestBehavior.AllowGet);

        }//end f show chart action

        

        }//controller
	}//namespace

Major_Project/Views/Analysis/Index.cshtml
@model IEnumerable<Major_Project.Models.item>

@{
    ViewBag.Title = "Index";
}

@if (Request.QueryString["message"] != null)
{
    <div class="alert alert-warning">Product already exists in a cart!!!</div>
}

<div class="container"><h2>Details</h2></div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            @{
                var DetailName = "/images/" + ViewBag.ID + ".jpg";
            }
            <img src="@DetailName" class="detailimage" />
        </div>
        <div class="col-md-8 capitalize">
            <table class="table table-hover">
                <tr>
                    <th>Name</th>
                    <td align="left">@ViewBag.Name</td>
                </tr>
                <tr>
                    <th>Category</th>
                    <td align="left">@ViewBag.Category</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td align="left">@ViewBag.Price</td>
                </tr>
            </table>

            <div class="container">
                @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = ViewBag.ID }, new { @class = "btn btn-warning" })
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-1">Bar Chart</button>
                <div class="modal fade" id="modal-1">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times</button>
                                <h3>Detail Chart</h3>

                            </div>
                            <div class="modal-body">
                                <div id="canvas">



                                </div>
                            </div>
                            <div class="modal-footer">
                                <a href="" class="btn btn-default" data-dismiss="modal">Close</a>

                                @*<a href="" class="btn btn-primary">Download</a>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div> @*modal container *@
        </div>   @*grid*@


    </div> @*row div*@
</div>


<div class="container">
    @*recommended items*@
    <br />
    <br />
    <div class="well well-sm"><h4><b>RECOMMENDED ITEMS</b></h4></div>
    <br />
    <div class="row">
        @foreach (var x in Model)
        {
            var imageName = "/images/" + @x.item_id + ".jpg";


       <!-- <div class="col-sm-6 col-md-3">-->
            <div class="col-lg-2 col-md-2 col-xs-6 thumb">
                <a href="@Url.Action("Index", "Analysis", new { id = x.item_id }, null)">
                    <div class="thumbnail">
                        <img src="@imageName" />

                    </div>
                </a>
                <div class="caption capitalize">
                    <div class="caption capitalize">
                        <h6><span class="glyphicon  glyphicon-shopping-cart"></span>@Html.DisplayFor(model => x.item_name)</h6>
                        @*<h6>@Html.DisplayFor(model => x.item_id)</h6>*@
                    </div>
                </div>
            </div>
        }

    </div>
</div>




<div class="container">
    @*other items*@
    <br />
    <br />
    <div class="well well-sm"><h4><b>OTHER ITEMS</b></h4></div>
    <br />
    <div class="row">
        @foreach (var x in ViewBag.items)
        {
            var imageName = "/images/" + @x.item_id + ".jpg";


             <!-- <div class="col-sm-6 col-md-3">-->
            <div class="col-lg-2 col-md-2 col-xs-6 thumb">
                <a href="@Url.Action("Index", "Analysis", new { id = x.item_id }, null)">
                    <div class="thumbnail">
                        <img src="@imageName" />
                    </div>
                </a>
                <div class="caption capitalize">
                    <div class="caption capitalize">
                        <h6><span class="glyphicon  glyphicon-shopping-cart"></span>@x.item_name</h6>
                        @*<h6>@Html.DisplayFor(model => x.item_id)</h6>*@
                    </div>
                </div>
            </div>
        }

    </div>
</div>







<script>
    var data;


    console.log(@ViewBag.ID);
    $.ajaxSetup({
        async: false
    });
    $.getJSON('@Url.Action("ShowChart", "Analysis", new { id = @ViewBag.ID},null)', function (result) {


        assign(result);

    });
    function assign(value) {

        //console.log(data);
        data = value;
    };
    console.log(data);
    var map = data.map(function (i) {
        return parseInt(i.y2);
    });
    var colorscale = d3.scale.ordinal()
                       .range(["#b05739", "#f73f00", "#dd3900", "#836527", "#616161"]);
    //.domain([0, d3.max(map)])
    //.range(["red","black"]);
    var xScale = d3.scale.linear()
                        .domain([0, function (d) { return data.length; }])
                        .range([0, 500]);

    var yScale = d3.scale.linear()
                        .domain([d3.max(map), 0])
                        .range([0, 450]);

    var axis = d3.svg.axis()
                        .ticks(data.length)
                        .scale(xScale);
    var axis2 = d3.svg.axis()
                        .ticks(10)
                        .orient("left")
                        .scale(yScale);



    var canvas = d3.select("#canvas")
                     .append("svg")
                     .attr("height", 500)
                     .attr("width", 600);
    var xaxisText = canvas.selectAll("text")		//text i.e product names
                        .data(data)
                        .enter()
                            .append("text")
                            .text(function (d) { return d.label; })
                            .attr("x", function (d) { return d.x2; })
                            .attr("transform", "translate(20,0)")
                            .attr("fill", "steelblue")
                            .attr("y", 470);
    var line = canvas.selectAll("line")	//dsh lines or bar lines
            .data(data)
            .enter()
                .append("line")
                .attr("x1", function (d) { return d.x2; })
                .attr("y1", function (d) { return yScale(d.y2); })
                .attr("x2", function (d) { return d.x2; })
                .attr("y2", 450)
                //.style("stroke-dasharray", ("5, 5"))
                .attr("transform", "translate(35,0)")
                .attr("stroke", function (d) { return colorscale(d.y2) })
                .attr("stroke-width", 50);

    canvas.append("g") //y axis
               .attr("transform", "translate(30,0)")
               .attr('class', 'axis')
                .attr("stroke-width", 1)
                .attr("fill", "steelblue")
               .call(axis2);

    canvas.append("line") // x axis
                .attr("x1", 15)
                .attr("y1", 450)
                .attr("x2", 600)
                .attr("y2", 450)
                .attr("stroke", "steelblue")
                //.style("stroke-dasharray", ("5, 5"))
                .attr("transform", "translate(10,0)")
                .attr("stroke-width", 2);

    canvas.append("text")
            .text("Items")
            .attr("x", 350)
            .attr("y", 490)
            .attr("fill", "steelblue");



</script>